### PR TITLE
Do not crash if non-prefixed AudioContext isn't available

### LINKED ISSUE #9: Crash in Safari 11.1.2
When using the polyfill in Sierra (10.12.6) and Safari 11.1.2, it crashes on the following code:

```js
  Object.defineProperty(AudioContext.prototype, 'audioWorklet', {
    get () {
      return this.$$audioWorklet || (this.$$audioWorklet = new window.AudioWorklet(this));
    }
  });
````

AudioContext isn't defined so this gives a `Can't find variable AudioContext`.

### PR DESCRIPTION
**Pull request by warpdesign**
Safari 11.x only has prefixed `webAudioContext`: without this patch the polyfill crashes.

Fixes #9

### CODE REVIEW

**Comment by warpdesign** [comment]
I signed it.

File: src/index.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ if (typeof AudioWorkletNode !== 'function') {
     return scriptProcessor;
   };
 
-  Object.defineProperty(AudioContext.prototype, 'audioWorklet', {
+  Object.defineProperty((window.AudioContext||webkitAudioContext).prototype, 'audioWorklet', {
```
Comment (developit) [inline src/index.js:50]: this will crash if neither are defined. Need to do:

```js
(self.AudioContext || self.webkitAudioContext)
```

**Review by developit — CHANGES_REQUESTED** [review]
just a small change - I can make it if you want, or you can!

**Comment by developit** [comment]
FWIW I usually recommend "polyfilling" AudioContext in Safari globally:

```js
if (!window.AudioContext && window.webkitAudioContext) = window.AudioContext = window.webkitAudioContext;
```

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Shipped in [1.1.1](https://github.com/GoogleChromeLabs/audioworklet-polyfill/releases/tag/1.1.1)! Cheers.

**Comment by warpdesign** [comment]
My app now work perfectly in Safari & Firefox!
